### ISSUE TITLE
In canal.yaml file  no etcd_endpoints: "....."  ?!

### ISSUE THREAD

**Issue by ltgzs777** [projectcalico/canal#75]
In canal.yaml file：
```
data:
  # The interface used by canal for host <-> host communication.
  # If left blank, then the interface is chosen using the node's
  # default route.
  canal_iface: ""
  # Whether or not to masquerade traffic to destinations not within
  # the pod network.
  masquerade: "true"
```
here is no etcd_endpoints: "....."  ?!
