### ISSUE TITLE
Network policy ingress from external ip 

### ISSUE THREAD

**Issue by prasenforu** [projectcalico/canal#87]
Environment:
Kubernetes 1.7 using kubeadm 
CNI: Canal

In network policy we define ingress from pod 
But I want from external ip.

Not sure How I can implement?

**Comment by tmjd** [comment]
One of the first questions we need to answer is, are you using an etcd backed Calico or is it using Kubernetes API as the datastore?
Using the Kubernetes API as the datastore is relatively new and does not yet support this but we're working on adding full Calico policy model support.  If you are using etcd as the backend then it might be possible depending on what you are specifically trying to do.

Is the traffic you are trying to block/allow going to be destined for the pod or will the traffic actually be going to a K8s service NodePort and then be passed to the pod?
If the traffic is destined directly for the pod then it is possible to write 'Calico' policy (not Kubernetes Network Policy) to allow or block the traffic.  With something like:
```
calicoctl apply -f - <<EOF
apiVersion: v1
kind: policy
metadata:
  name: allow-from-remote-ip
spec:
  selector: calico/k8s_ns == '<k8s namespace>'
  order: 500
  egress:
  - action: allow
    source:
      net: 10.0.128.128/32
EOF
```
Please checkout http://docs.projectcalico.org/v2.3/getting-started/kubernetes/tutorials/advanced-policy and http://docs.projectcalico.org/v2.3/reference/calicoctl/resources/policy to help with writing the correct policy for your setup.

If your traffic is going to be destined for a NodePort service then allowing that traffic is a bit more complicated as a NodePort service re-writes source addresses and therefore it is not possible to write policy that applies to pods that filters on source addresses.
